version: '2'
services:
  d7:
    build: .
    image: zilleem-d7:1 
    volumes:
      - $PWD/html:/var/www/html
    ports:
      - "80:80"
    links:
      - db
      - redis
      - solr
  db:
    image: mysql
    volumes:
      - $PWD/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  redis:
    image: redis:2.8
    ports:
      - "6379"
  solr:
    build: solr/
    ports:
      - "8983:8983"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions
