version: '2'
services:
  wp:
    build: .
    image: zilleem-wp:1.0
    volumes:
      - $PWD/html:/var/www/html
    ports:
      - "8082:80"
    links:
      - db
      - redis
  db:
    image: mysql
    volumes:
      - $PWD/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  redis:
    image: redis:2.8
    ports:
      - "6379"
